# Generated by Django 4.2.4 on 2023-08-17 01:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0002_subject_content_alter_section_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
