# Generated by Django 4.2.4 on 2023-08-17 04:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0003_alter_subject_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
